spring:
  cloud:
    gateway:
      routes:
        - id: id001
          uri: http://localhost:8081/
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1