server:
  port: 8089
application:
  name: common-config
  version: 1.0
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: d:/test/config